### ISSUE TITLE
Platform question

### ISSUE THREAD

**Issue by DChinin** [DarkPark/stb#6]
Is it only for MAG? Or you plan to support other STB, such as Dune, Humax, Albis etc
When you plan to support platform-specific functionality (mac/ip/player) ?

**Comment by DarkPark** [comment]
At the moment it is linked to STB but in general there is very little specific code.
The main purpose is to easily create SPA with remote/keyboard control.
Support other STB and platform-specific functionality is not implemented at the moment but due to the architecture (release build is compiled without any dev functionality (or any not target platforms in future) - the most compact form) it shouldn't be difficult.

**Comment by DenisChinin** [comment]
Ok, i will wait for platform functions. 

One more question: why you start a new project instead of fork/improve `inio` project?  STB framework is very similar to them

**Comment by DarkPark** [comment]
I haven't seen this project before. Will take a closer look.
But in general main idea of this project was performance.
No jquery, react or similar. People who believe these libraries are lightweight and quick probably never tried to use them on regular very hardware-modest devices like mag250 and take a look at profiling results - 50 and more levels of stack, 150 ms just to move focus from button to button and so on.
So this framework uses only native JS with a lot of low-level optimizations and approaches.

**Comment by DenisChinin** [comment]
Yes, perfomance is a huge problem on STB.  And there many ways to increase perfomance on different devices. And that the reason why i asked you about frameworks platforms.

**Comment by DarkPark** [comment]
I'm not familiar with other platforms so there should be some interest from experienced people to add these platforms to the framework.
